"""changes to game model

Revision ID: becd63df4dfe
Revises: 69252676b9f1
Create Date: 2025-07-20 21:23:30.619244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becd63df4dfe'
down_revision: Union[str, Sequence[str], None] = '69252676b9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_game_platform_game_id'), table_name='game_platform')
    op.drop_index(op.f('idx_game_platform_platform_id'), table_name='game_platform')
    op.drop_index(op.f('idx_game_name_year'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_year'), table_name='games')
    op.create_unique_constraint('uq_game_name_year', 'games', ['name', 'year'])
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.create_unique_constraint(None, 'platforms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.drop_constraint('uq_game_name_year', 'games', type_='unique')
    op.create_index(op.f('ix_games_year'), 'games', ['year'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('idx_game_name_year'), 'games', ['name', 'year'], unique=False)
    op.create_index(op.f('idx_game_platform_platform_id'), 'game_platform', ['platform_id'], unique=False)
    op.create_index(op.f('idx_game_platform_game_id'), 'game_platform', ['game_id'], unique=False)
    # ### end Alembic commands ###
